apiVersion: apps/v1
kind: Deployment
metadata:
  name: "tester-deployment"
  namespace: "tester-ns"
  labels:
    app: "tester"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "tester"
  template:
    metadata:
      labels:
        app: "tester"
    spec:
      containers:
        - name: "tester"
          image: "andersonmtu/tavern-tests"
          command: ["sleep 9000000"]