# permissions for end users to view testrunners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: testrunner-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: tester-operator
    app.kubernetes.io/part-of: tester-operator
    app.kubernetes.io/managed-by: kustomize
  name: testrunner-viewer-role
rules:
- apiGroups:
  - operator.anderson.com
  resources:
  - testrunners
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.anderson.com
  resources:
  - testrunners/status
  verbs:
  - get
